[colors.primary]
background = '#1a1209'
foreground = '#f2dfd1'

[colors.selection]
text = '#f2dfd1'
background = '#443e7f'

[colors.cursor]
text = '#1a1209'
cursor = '#c6c0ff'

[colors.normal]
black   = '#1a1209'
red     = '#e25043'
green   = '#6ed672'
yellow  = '#dbd77b'
blue    = '#8271e8'
magenta = '#9d99bf'
cyan    = '#c6c0ff'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e0665f'
green   = '#86e089'
yellow  = '#e8e497'
blue    = '#d3cdff'
magenta = '#6f70ca'
cyan    = '#806eb9'
white   = '#ffffff'
